# Generated by Django 4.2.6 on 2023-12-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('actor_name', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=100)),
                ('total_cost', models.IntegerField()),
            ],
        ),
    ]
