# Generated by Django 4.2.6 on 2023-12-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='total_cost',
            field=models.CharField(max_length=100),
        ),
    ]
