# Generated by Django 4.2.6 on 2023-12-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_alter_movie_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_age', models.IntegerField()),
                ('total_people', models.IntegerField()),
                ('number_of_male', models.IntegerField()),
                ('number_of_female', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
                ('required_seats', models.IntegerField()),
            ],
        ),
    ]
